### PR TITLE
Add monorepo/group support for the Neutrino project

### PR DESCRIPTION
**Pull request by edmorley**
See:
https://github.com/mozilla-neutrino/neutrino-dev/tree/master/packages

CC @eliperelman

### CODE REVIEW

**Comment by edmorley** [comment]
CC @eliperelman

**Comment by eliperelman** [comment]
@edmorley would this exclude the main `neutrino` package?

**Comment by eliperelman** [comment]
Nevermind, I think the combination of `packageNames` and `packagePatterns` covers that.

**Comment by edmorley** [comment]
Yeah using both works:
https://github.com/renovateapp/renovate/issues/1313#issuecomment-352876285

**Pull request merged**
