### PR TITLE
Add group preset for browser-logos

### PR DESCRIPTION
**Pull request by Hexcles**
Source: https://github.com/alrra/browser-logos
NPM: https://www.npmjs.com/org/browser-logos

### CODE REVIEW

**Comment by Hexcles** [comment]
cc @alrra

**Comment by Jamesking56** [comment]
This group of packages doesn't have matching version numbers or update at the same time, so is there a point to having the grouping?

**Comment by Hexcles** [comment]
They do often update at the same time (but not always), usually for "optimizing images". Perhaps the maintainer could chime in here @alrra ?

**Comment by alrra** [comment]
> This group of packages doesn't have matching version numbers or update at the same time

Yes, they are, and should be treated as individual packages.

> They do often update at the same time (but not always), usually for "optimizing images"

It's rare for all of them to get new releases at the same time (see the individual changelogs), but when it happens is because: 
  
   * something is added or removed from all the `package.json` / `README.md` files (e.g: https://github.com/alrra/browser-logos/commit/896ab303b43decd25c518ea5dc0081e6974d344a)
   * there is a new way / new tools to better optimize images, in which case, most or all packages will be updated (but this has been happening less frequently in the past period)

**Comment by Jamesking56** [comment]
I think the real distinguishing thing here is.

The groups in Renovate are for packages which should match releases (not necessarily version numbers). For example, `phpstan` has extensions such as `phpstan-deprecation-rules`; these should be updated together because `phpstan` might not be compatible with the extension if their version numbers / release do not match each other.

So, if a project has two different `@browser-logos` packages installed, If Renovate only updated one of them would it cause an incompatibility / bug to appear due to the releases not matching? I think in this case since they are just images that would be a no. Therefore doesn't need a grouping?

Would you agree with that reasoning @alrra @Hexcles ?

**Comment by rarkins** [comment]
I would like for Renovate to support two types of groupings:
- Ones that are mandatory to upgrade together all or most of the time, so we always group them
- Ones that are related and beneficial to group together in Renovate PRs, although not mandatory

I think it's ok to add a grouping like this PR's as-is because it's not being bundled up with the `group:monorepos` or `group:recommended` rules that are part of `config:base`.

Note: it's still needed for someone to run `node generate.js` and commit the updated `package.json` too.

**Comment by alrra** [comment]
> So, if a project has two different @browser-logos packages installed, If Renovate only updated one of them would it cause an incompatibility / bug to appear due to the releases not matching? I think in this case since they are just images that would be a no.

@Jamesking56 Yes, that would **not** cause any incompatibility. They are independent of each other, and the only reason why they are in a monorepo is because it makes maintenance easier.

**Comment by Hexcles** [comment]
I see. I'm convinced then. Thanks for all the explanation, everyone! Feel free to close it or take it (as suggested by @rarkins ), whichever is more consistent with the the convention.

**Comment by rarkins** [comment]
We have refactored the structure of this repository completely, so it's best to start a new PR if still interested. Sorry for any inconvenience

**Pull request closed without merging**
