### PR TITLE
Group all packages by Font Awesome together

### PR DESCRIPTION
**Pull request by astorije**
We're relying on multiple repositories from @fortawesome, and they often update them in the same timeframe, Renovate then opening multiple PRs at the same time. Case in point, latest @fortawesome/fontawesome-svg-core and @fortawesome/free-solid-svg-icons were both released within a minute.

We haven't yet seen a hard dependency between these repos, making grouping mandatory, but it sure would be nice if those package upgrades were bundled together.

Related:

- https://github.com/renovatebot/presets/issues/46
- https://github.com/renovatebot/config-help/issues/38

Thoughts?

### CODE REVIEW

**Comment by rarkins** [comment]
Yes I think this sounds ok

**Comment by astorije** [comment]
Great @rarkins! I have rebased my branch on top of master to resolve the "outdated branch" status check.

**Comment by astorije** [comment]
@rarkins, I have a couple open (untouched) Renovate PRs for `@fortawesome/*` packages, can you confirm that I should just leave those alone, and Renovate will correctly close them and open a consolidated one accordingly whenever you deploy this change to the bot?

**Comment by rarkins** [comment]
Yes they should get autoclosed it all is working as expected

**Pull request merged**
