### PR TITLE
Add a few Apollo packages to the apolloclient monorepo preset

### LINKED ISSUE #2120: New preset: apollo-client monorepo + react-apollo
Hi there!

Today, the [`apollo-client` monorepo](https://github.com/apollographql/apollo-client) updated their packages, and we could see Renovate picking them up correctly. Later on, the [`react-apollo` repo/package](https://github.com/apollographql/react-apollo) was published, and again, Renovate picked it up just fine.
However, those were all depending on each other, so our 2 PRs failed, and needed to be combined.

Would you be open to a new preset that combines the Apollo packages mentioned above? If so, I would be happy to give it a shot :)

For context, we only extend the base config + rebaseStalePrs preset for now.

### PR DESCRIPTION
**Pull request by astorije**
Resolves https://github.com/renovateapp/renovate/issues/2120.

This is not exhaustive, as this simply reflects what packages we rely on in our organization. I did not want to go all out and include everything there is, only what we see as valuable grouped together. These additions are packages from these repos:

- https://github.com/apollographql/apollo-link
- https://github.com/apollographql/graphql-tag
- https://github.com/apollographql/react-apollo

I have created a new `monorepo` preset (and corresponding `group` preset) for https://github.com/apollographql/apollo-link, as well as a `packages` preset to start putting all those packages together (this is what resolves Resolves https://github.com/renovateapp/renovate/issues/2120, essentially) and a corresponding `group` preset.
 
Overall, the new presets are now available:

- `group:allApollographql`
- `group:apollolinkMonorepo`
- `monorepo:apollolink`
- `packages:apollographql`

I also updated `monorepo` initially per the contributing guidelines.

### CODE REVIEW

**Comment by rarkins** [comment]
This won't work because the `package.json` is actually generated, so it will get overridden the next time. Also, they should not be added to the monorepo's group because it should exist on its own like all the other monorepos - this should be a separate group/rule.

**Comment by astorije** [comment]
> Do not edit the `package.json` directly.

🤦‍♂️
I need to learn how to read.
Alright, be back in a few for take two!

**Comment by astorije** [comment]
@rarkins, I am done now, and I think I much better understand how everything fits together. Let me know if I messed something up!

I would love to add `group:allApollographql` to the `config:base` preset because, at the end of the day, it's making sure that `apollo-client` and `react-apollo` are updated together that resolves https://github.com/renovateapp/renovate/issues/2120 and fixes underlying issues, but I'm not sure if there is a good place for that already. Let me know if/how I could do that in a decent way.

Thanks for your help!

**Comment by rarkins** [comment]
@astorije this is looking clever, although it can be easy to make small mistakes so I'll need to double check it later. I think it sounds OK to add it as a base preset.

**Comment by astorije** [comment]
Thanks @rarkins!

> I think it sounds OK to add it as a base preset.

Is there a specific place you would want me to do that? Or just add it [here](https://github.com/renovatebot/presets/blob/7d432ff37044d22b4416329afee4c0313190283d/packages/renovate-config-config/package.json#L35) (that feels wrong, but I don't see another preset to group it with)?

**Comment by astorije** [comment]
Hey @rarkins, did you get a chance to look at this PR? 🙏
Still unsure what is the best way to add this to the base config, so your advice is welcome :)

**Comment by rarkins** [comment]
@astorije sorry for the delay. The answer is not simple, so I was "thinking" about it. I'm not sure whether to manually combine these into a single "monorepo" rule (even though technically it's 2 source repos) or to introduce a new concept/rule that `config:base` uses instead

**Comment by astorije** [comment]
I think introducing a new concept/rule and putting it into `config:base` makes sense. Not sure how to name it though :D

**Comment by rarkins** [comment]
@astorije thanks for this contribution. Can you please verify that these groups now work as you intended? Once that's done, I'll work out how to add them gracefully to `config:base`. For now you'll need to add them *after* it so that they override default monorepo groupings.

**Comment by astorije** [comment]
Sounds good, I'll try that for now, thanks!

**Comment by astorije** [comment]
I can now confirm the following works as expected:

```json
{
  "extends": [
    "config:base",
    "group:allApollographql"
  ]
}
```

screen shot 2018-07-25 at 17 59 11

**Comment by astorije** [comment]
Hey @rarkins, any chance you could consider adding this preset as part of the base config? We've been using this on some of our repos very happily and would love if all repos could benefit from it for free! 🙏

**Comment by rarkins** [comment]
@astorije yes, I think I will

**Comment by astorije** [comment]
Awesome, looking forward to it :)

**Comment by rarkins** [comment]
@astorije now added as part of a new "group:recommended" to "config:base"

**Comment by astorije** [comment]
Great news, thanks @rarkins!

**Pull request merged**
