### PR TITLE
Added the hapijs monorepo

### PR DESCRIPTION
**Pull request by DamianStanger**
The node hapi ecosystem (https://hapi.dev/) is large and it would be useful to group all hapijs related updates together.

### CODE REVIEW

**Comment by rarkins** [comment]
@DamianStanger I'm not able to update this branch from master (perhaps permissions if you didn't grant maintainers access):

image

Could you please update and then perform any corrections is possible? I enabled `prettier` checks so I think that your formatting change will likely cause a failure once rebased.

**Comment by DamianStanger** [comment]
@rarkins ive have given access for maintainers to update this branch
Will look into prettier now

**Comment by DamianStanger** [comment]
Its all green now @rarkins

**Comment by rarkins** [comment]
Thanks @DamianStanger. I've merged and published. Tomorrow I'll update the associated grouping settings so that it's pulled in by default

**Pull request merged**
