### PR TITLE
feat(monorepo): add sanity repo

### PR DESCRIPTION
**Pull request by pvinis**
originated here https://github.com/renovatebot/renovate/issues/4713

### CODE REVIEW

**Comment by rarkins** [comment]
Hi @pvinis thanks for your contribution. You will need to edit this PR first though. Please see the instructions here: https://github.com/renovatebot/presets/tree/master/packages/renovate-config-monorepo for how to contribute. You need to edit the .js file and not the .json file directly.

**Comment by pvinis** [comment]
Oopsssss, that's what I get from trying to make a PR quickly from my phone :D Fixing it now.

**Comment by rarkins** [comment]
Thanks, can you also run "node generate" in that directory so that the package.json content is updated automatically? Then I can merge in one commit.

**Comment by pvinis** [comment]
I did, that's how it was added in the file :D I reverted my original commit.

**Comment by rarkins** [comment]
Great, thanks. I need to do some publishing work after this, the affects of this should be live within a few hours if all goes well

**Pull request merged**
