### PR TITLE
Provide monorepo for Swashbuckle

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Wanted to run `node generate.js` but it fails with following error:
```
⚡ tkerkhove@CLT-TKERKHOVE  C:\Code\GitHub\presets\packages\renovate-config-monorepo   swashbuckle ≢ ~1 -0 !                                                                                                                                                        [11:03]
❯ node generate.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@sindresorhus/is'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Code\GitHub\presets\packages\renovate-config-monorepo\generate.js:1:74)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Tried undoing my change to see if it's because of me but even then I have the same issue. Any input on how to fix this?

**Comment by tomkerkhove** [comment]
I didn't run the generation due to https://github.com/renovatebot/presets/issues/170 but see that other PRs were merged after this one.

Do you want me to open a PR to run the generation again @rarkins?

**Comment by tmack8001** [comment]
@tomkerkhove I still get an error when trying to generate even from master and my PRs were the others that were merged also missing the generation.

**Comment by rarkins** [comment]
You need to run `yarn` from the root directory of this repository. After that `node generate` should work in any of the subdirectories.

**Comment by tmack8001** [comment]
No need to regenerate as @rarkins did that in https://github.com/renovatebot/presets/commit/d96e05eb2a230834989323b524dc84075757a1f0

**Pull request merged**
