### PR TITLE
Rename "Fort Awesome" into "Font Awesome"

### PR DESCRIPTION
**Pull request by astorije**
Teeny tiny change, but the fort/font difference is rather confusing, and at the moment Renovate opens PRs titled "Update Fort Awesome" (but hey, it works, thanks for merging #87!) which I know for a fact that I will always miss when I grep/search :D

### CODE REVIEW

**Comment by rarkins** [comment]
I'm not sure I like this change actually. Although small, it will result in any PRs which have been created in the last hour to be autoclosed and reopened, because the branchname will change (Technically we could have branch stay same though, but it could be more confusing).

But secondly, Fort Awesome and Font Awesome *are* technically different things, and I'm not sure it's right for us to use the old name instead of the correct one.

**Comment by astorije** [comment]
Those are good points, thanks @rarkins.
However, from a consumer point of view, it's just weird and confusing to see PRs named "Update Fort Awesome" when my project uses, in fact, Font Awesome.

Fort Awesome is the name of their organization while Font Awesome is the name of the project people use.

Anyway, feel free to take this PR or close it, but my 2c as a user is that my dependency is on Font Awesome (the project / library) and not Fort Awesome (the company).
Either way, small detail, it's really nice this is now grouped as it already fixed one of the dependency update PRs 👌 Thanks!

**Comment by rarkins** [comment]
Hmm ok, I see what you mean. It’s very confusing now that their new commercial product is also called Fort Awesome while their older open source offering is published using the `@fortawesome` namespace. Perhaps we leave the branch name as renovate/fort-awesome and adjust the PR title to “Font Awesome”?

**Comment by astorije** [comment]
> while their older open source offering is published using the `@fortawesome` namespace

In fact, even the latest Font Awesome libs are under this namespace.

> Perhaps we leave the branch name as renovate/fort-awesome and adjust the PR title to “Font Awesome”?

Sounds good to me!

I have rebased this branch, let me know if there is anything I need to change (or feel free to add commits to my branch).

**Comment by astorije** [comment]
Rebased again to keep it in a mergeable state.

**Comment by rarkins** [comment]
It’s ok for it to behind master actually (I merge squash) but I need to bump the version and then pull locally to publish after merge.

**Comment by astorije** [comment]
Ah, sounds good, I wasn't sure what was the most convenient for you :)

**Comment by rarkins** [comment]
For future reference, most convenient is:

- make sure package.json are always updated too
- bump the package json version
- rebase/update only if there’s a merge conflict. 

That way I don’t need to make any additional commits to the repo before or after merge.

**Comment by astorije** [comment]
Good to know! I believe I have done all 3 now :)

**Comment by astorije** [comment]
@rarkins, it looks like the release notes do not get populated in the PR the bot opens. Do you know why that is? It's on a private repo so unfortunately I cannot share here :/

**Comment by rarkins** [comment]
What’s an example package with no release notes but you can find them on GitHub?

**Comment by astorije** [comment]
So I did a random search on GitHub and https://github.com/jaxx2104/gatsby-starter-bootstrap/pull/132 is similar to what I'm seeing in our private repo. Check out the empty "Release notes" section.

**Comment by astorije** [comment]
Hey @rarkins, did you get a chance to look into that?
Do you need me to create a dedicated issue for this? If so, which repo would you rather have this on?

Thanks!

**Comment by rarkins** [comment]
Sorry, I overlooked it earlier. Can you create an issue in the main repo?

**Pull request merged**
